Repository ds5105119/tangerineAPI, pull requests merged in 2024-10, with the labels that each got.

#104 [O] views.py :lookup_field , lookup_url_kwarg [O] urls.py : re_path -> path
  products/urls.py
  products/views.py
Labels: enhancement

#108 accounts, chats 앱 리팩토링
  accounts/permissions.py
  accounts/serializers.py
  accounts/views.py
  channels_pulsar/layer.py
  channels_pulsar/middlewares.py
  chats/consumers.py
  chats/models.py
  chats/permissions.py
  chats/serializers.py
  chats/views.py
  config/settings/base.py
  start.sh
Labels: issue

#109 - [O] RecommendProductsAPIViewSet 수정 (Mixin 사용) - [O] urls.py 수정
  products/urls.py
  products/views.py
Labels: wontfix

#121 전체 앱 리팩토링 및 추천, 검색 엔진 구현
  .gitignore
  accounts/models.py
  accounts/serializers.py
  accounts/views.py
  chats/paginators.py
  chats/serializers.py
  chats/views.py
  comments/models.py
  config/gunicorn_config.py
  config/settings/base.py
  config/settings/dev.py
  config/settings/docker_dev.py
  docker-compose.yml
  follows/views.py
  images/models.py
  images/serializers.py
  images/services.py
  images/urls.py
  images/views.py
  old/channels_pulsar/__init__.py
  old/channels_pulsar/layer.py
  old/channels_pulsar/manager.py
  old/channels_pulsar/middlewares.py
  posts/apps.py
  posts/documents.py
  posts/models.py
  posts/permissions.py
  posts/serializers.py
  posts/services.py
  posts/urls.py
  posts/views.py
  pyproject.toml
  start.sh
  tests/_likes.py
Labels: bug, enhancement, issue

#124 Tg 120 issue 123
  config/settings/base.py
  docker-compose-prod.yml
  docker-compose.yml
  posts/urls.py
Labels: bug

#128 docker compose production용 수정
  docker-compose-prod.yml
Labels: issue

#132 docker compose production용 수정
  .github/workflows/deploy.yml
  docker-compose-prod.yml
Labels: enhancement, issue

#133 docker compose production용 수정
  docker-compose-prod.yml
Labels: enhancement

#114 - [O] Report App 생성 - [O] model 작성 - [O] serializers 작성 - [O] permissions 작성 - [O] views 작성 - [O] urls 작성
  reports/__init__.py
  reports/admin.py
  reports/models.py
  reports/permissions.py
  reports/serializers.py
  reports/urls.py
  reports/views.py
Labels: issue

#136 TG-124--issue-135
  readme.md
  readme_img/code_review.png
  readme_img/github_codeql.png
  readme_img/issue_templates.png
  readme_img/jira.png
  readme_img/jira_github_autointerconnection.png
  readme_img/notion.png
Labels: documentation

#143 [O] apps.py 생성 [O] base.py 연결
  config/settings/base.py
  reports/apps.py
Labels: issue
